#include <avr/io.h>

#define ws2812b_zero(port,bit) \
    __asm__ __volatile__("sbi %[A], %[b]" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "cbi %[A], %[b]" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" \
                         : \
                         : [A] "I" _SFR_IO_ADDR(port), \
                           [b] "I" (bit));

#define ws2812b_one(port,bit) \
    __asm__ __volatile__("sbi %[A], %[b]" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "cbi %[A], %[b]" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" \
                         : \
                         : [A] "I" _SFR_IO_ADDR(port), \
                           [b] "I" (bit));

#define ws2812b_reset(port,bit) \
    __asm__ __volatile__("cbi %[A], %[b]" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" "\n\t" \
                         "nop" \
                         : \
                         : [A] "I" _SFR_IO_ADDR(port), \
                           [b] "I" (bit));
